import React, { useState } from 'react';
import { 
  X, 
  CheckCircle2, 
  AlertTriangle, 
  Download, 
  Send, 
  Printer, 
  RefreshCw, 
  FileCheck, 
  Layers,
  ZoomIn,
  Phone,
  Truck,
  Building2,
  DollarSign
} from 'lucide-react';
import { useAdmin } from '../../context/AdminContext';

export const PreflightFileInspector = () => {
  const { 
    selectedOrder, 
    preflightModalOpen, 
    setPreflightModalOpen, 
    updateOrderStatus 
  } = useAdmin();

  const [showBleedOverlay, setShowBleedOverlay] = useState(true);
  const [showSafetyOverlay, setShowSafetyOverlay] = useState(true);
  const [zoomLevel, setZoomLevel] = useState(1);

  if (!preflightModalOpen || !selectedOrder) return null;

  const art = selectedOrder.artworkFile || {
    fileName: "Uploaded_Artwork_File.pdf",
    fileType: "pdf",
    dimensions: "91mm x 53mm",
    resolutionDpi: 300,
    cmykVerified: true,
    hasBleed: true,
    previewUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=1200&auto=format&fit=crop"
  };

  const sendWhatsAppProof = () => {
    const message = `Hello ${selectedOrder.customer.name}, your pre-flight print proof for Order ${selectedOrder.id} has been generated by Printigly. View proof: ${art.previewUrl}`;
    window.open(`https://wa.me/${selectedOrder.customer.phone.replace(/[^0-9]/g, '')}?text=${encodeURIComponent(message)}`, '_blank');
  };

  const generateShippingSlip = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-5xl h-[90vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        
        {/* Modal Top Bar */}
        <div className="p-4 border-b border-slate-200 bg-white text-slate-950 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600 font-extrabold shadow-sm border border-blue-150">
              <FileCheck className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-extrabold text-base tracking-tight text-slate-900">
                  Pre-Flight File Inspector & Inspector Engine
                </h3>
                <span className="px-2 py-0.5 rounded bg-blue-50 text-blue-700 font-extrabold text-xs border border-blue-200">
                  {selectedOrder.id}
                </span>
              </div>
              <p className="text-xs text-slate-500">
                Customer: {selectedOrder.customer.name} ({selectedOrder.customer.company || 'Retail'})
              </p>
            </div>
          </div>

          <button
            onClick={() => setPreflightModalOpen(false)}
            className="p-1.5 rounded-xl bg-slate-50 hover:bg-slate-100 text-slate-450 hover:text-slate-700 transition-colors border border-slate-200/60 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Main Body Grid */}
        <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 overflow-y-auto lg:overflow-hidden bg-slate-100">
          
          {/* Left Canvas Preview Area (2 cols) */}
          <div className="lg:col-span-2 p-6 flex flex-col items-center justify-center relative overflow-hidden bg-slate-900/90 border-r border-slate-800">
            
            {/* Bleed Overlay Controls Toolbar */}
            <div className="absolute top-4 left-4 right-4 z-20 flex flex-wrap items-center justify-between bg-slate-900/90 backdrop-blur-md border border-slate-700/80 rounded-xl p-2 text-xs text-white">
              <div className="flex items-center gap-3">
                <span className="font-bold text-slate-400 text-[10px] uppercase tracking-wider">Guide Overlays:</span>
                <label className="flex items-center gap-1.5 cursor-pointer font-medium text-red-400">
                  <input 
                    type="checkbox" 
                    checked={showBleedOverlay} 
                    onChange={(e) => setShowBleedOverlay(e.target.checked)} 
                    className="accent-red-500 rounded"
                  />
                  <span>3mm Outer Bleed Guide</span>
                </label>

                <label className="flex items-center gap-1.5 cursor-pointer font-medium text-emerald-400">
                  <input 
                    type="checkbox" 
                    checked={showSafetyOverlay} 
                    onChange={(e) => setShowSafetyOverlay(e.target.checked)} 
                    className="accent-emerald-500 rounded"
                  />
                  <span>Inner Safety Zone</span>
                </label>
              </div>

              <div className="flex items-center gap-2">
                <button 
                  onClick={() => setZoomLevel(prev => Math.max(prev - 0.2, 0.8))}
                  className="px-2 py-1 bg-slate-800 rounded hover:bg-slate-700 text-slate-300"
                >
                  -
                </button>
                <span className="font-mono text-xs">{Math.round(zoomLevel * 100)}%</span>
                <button 
                  onClick={() => setZoomLevel(prev => Math.min(prev + 0.2, 2.0))}
                  className="px-2 py-1 bg-slate-800 rounded hover:bg-slate-700 text-slate-300"
                >
                  +
                </button>
              </div>
            </div>

            {/* Artwork Canvas Frame */}
            <div className="relative flex items-center justify-center p-8 transition-transform duration-150" style={{ transform: `scale(${zoomLevel})` }}>
              <div className="relative bg-white rounded shadow-2xl overflow-hidden border-2 border-slate-700">
                <img 
                  src={art.previewUrl} 
                  alt="Preflight Artwork Preview" 
                  className="max-h-[420px] object-contain"
                />

                {/* 3mm Bleed Line Overlay (Red Border) */}
                {showBleedOverlay && (
                  <div className="absolute inset-0 border-4 border-dashed border-red-500/80 pointer-events-none flex items-start justify-start p-1">
                    <span className="bg-red-600 text-white text-[9px] font-bold px-1 rounded">3mm Bleed</span>
                  </div>
                )}

                {/* Safety Zone Overlay (Green Inner Border) */}
                {showSafetyOverlay && (
                  <div className="absolute inset-4 border-2 border-emerald-500/90 pointer-events-none flex items-end justify-end p-1">
                    <span className="bg-emerald-600 text-white text-[9px] font-bold px-1 rounded">Safety Zone</span>
                  </div>
                )}
              </div>
            </div>

            {/* Canvas Footer Status */}
            <div className="absolute bottom-4 left-4 text-xs font-mono text-slate-400">
              Format: {art.fileType.toUpperCase()} | Resolution: {art.resolutionDpi} DPI | Dim: {art.dimensions}
            </div>
          </div>

          {/* Right Pre-flight Audit Checklist & Quick Actions (1 col) */}
          <div className="p-5 flex flex-col justify-between overflow-y-auto bg-white">
            <div className="space-y-4">
              
              {/* Preflight Checklist Header */}
              <div>
                <h4 className="font-bold text-slate-900 text-sm mb-1">
                  Pre-Flight Automated Audit Results
                </h4>
                <p className="text-xs text-slate-500">Validation score calculated before press assignment</p>
              </div>

              {/* Checklist Items */}
              <div className="space-y-2.5">
                <div className="p-2.5 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-between text-xs">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span className="font-semibold text-emerald-900">CMYK Color Profile Verified</span>
                  </div>
                  <span className="font-mono text-[10px] text-emerald-700 font-bold">FOGRA39</span>
                </div>

                <div className="p-2.5 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-between text-xs">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span className="font-semibold text-emerald-900">300 DPI High-Res Print Density</span>
                  </div>
                  <span className="font-mono text-[10px] text-emerald-700 font-bold">Passed</span>
                </div>

                <div className="p-2.5 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-between text-xs">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span className="font-semibold text-emerald-900">3mm Cut Bleed Margins Detected</span>
                  </div>
                  <span className="font-mono text-[10px] text-emerald-700 font-bold">Valid</span>
                </div>

                <div className="p-2.5 rounded-xl bg-amber-50 border border-amber-200 flex items-center justify-between text-xs">
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="w-4 h-4 text-amber-600" />
                    <span className="font-semibold text-amber-900">Embedded Fonts Check</span>
                  </div>
                  <span className="font-mono text-[10px] text-amber-700 font-bold">Outlined</span>
                </div>
              </div>

              {/* Customer & GST Info Box */}
              <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 text-xs space-y-1.5">
                <div className="font-bold text-slate-900">Customer Shipping Details</div>
                <div className="text-slate-600 flex items-center gap-1.5">
                  <Phone className="w-3.5 h-3.5 text-slate-400" />
                  <span>{selectedOrder.customer.phone}</span>
                </div>
                <div className="text-slate-600 flex items-center gap-1.5">
                  <Building2 className="w-3.5 h-3.5 text-slate-400" />
                  <span>GSTIN: {selectedOrder.customer.gstin || 'Consumer Purchase'}</span>
                </div>
                <div className="text-slate-600 flex items-center gap-1.5">
                  <Truck className="w-3.5 h-3.5 text-blue-500" />
                  <span className="font-medium text-slate-800">{selectedOrder.deliveryMethod}</span>
                </div>
              </div>

            </div>

            {/* Quick Action Operational Buttons */}
            <div className="pt-4 border-t border-slate-200 space-y-2">
              <button
                onClick={sendWhatsAppProof}
                className="w-full py-2.5 px-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-xs transition-colors"
              >
                <Send className="w-4 h-4" /> Send Proof via WhatsApp
              </button>

              <button
                onClick={() => {
                  updateOrderStatus(selectedOrder.id, 'In Production');
                  setPreflightModalOpen(false);
                }}
                className="w-full py-2.5 px-3 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-xs transition-colors"
              >
                <Printer className="w-4 h-4" /> Mark In Production
              </button>

              <div className="grid grid-cols-2 gap-2">
                <button
                  onClick={generateShippingSlip}
                  className="py-2 px-3 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-semibold text-xs flex items-center justify-center gap-1.5 transition-colors"
                >
                  <Download className="w-3.5 h-3.5" /> Shipping Slip
                </button>

                <button
                  onClick={() => {
                    alert(`Refund initiated for Order ${selectedOrder.id} (₹${selectedOrder.totalAmount})`);
                  }}
                  className="py-2 px-3 rounded-xl bg-red-50 hover:bg-red-100 text-red-600 font-semibold text-xs flex items-center justify-center gap-1.5 border border-red-200 transition-colors"
                >
                  <DollarSign className="w-3.5 h-3.5" /> Issue Refund
                </button>
              </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
};
